# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'book_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        MainWindow.setWindowTitle("Book Price Finder")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setObjectName("verticalLayout_main")

        # ---- Row 1: Book Title / Find Price ----
        self.horizontalLayout_title = QtWidgets.QHBoxLayout()
        self.horizontalLayout_title.setObjectName("horizontalLayout_title")

        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setObjectName("label_title")
        self.label_title.setText("Book Title:")
        self.horizontalLayout_title.addWidget(self.label_title)

        self.lineEdit_title = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.horizontalLayout_title.addWidget(self.lineEdit_title)

        self.btn_find_price = QtWidgets.QPushButton(self.centralwidget)
        self.btn_find_price.setObjectName("btn_find_price")
        self.btn_find_price.setText("Find Price")
        self.horizontalLayout_title.addWidget(self.btn_find_price)

        self.verticalLayout_main.addLayout(self.horizontalLayout_title)

        # ---- Row 2: Price display ----
        self.horizontalLayout_price = QtWidgets.QHBoxLayout()
        self.horizontalLayout_price.setObjectName("horizontalLayout_price")

        self.horizontalSpacer_price = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_price.addItem(self.horizontalSpacer_price)

        self.label_priceLabel = QtWidgets.QLabel(self.centralwidget)
        self.label_priceLabel.setObjectName("label_priceLabel")
        self.label_priceLabel.setText("Price:")
        self.horizontalLayout_price.addWidget(self.label_priceLabel)

        self.label_price = QtWidgets.QLabel(self.centralwidget)
        self.label_price.setObjectName("label_price")
        self.label_price.setStyleSheet("color: blue;")
        self.label_price.setText("Rs. 0")
        self.horizontalLayout_price.addWidget(self.label_price)

        self.verticalLayout_main.addLayout(self.horizontalLayout_price)

        # ---- Separator line ----
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_main.addWidget(self.line)

        # ---- Vertical spacer ----
        self.verticalSpacer = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.verticalLayout_main.addItem(self.verticalSpacer)

        # ---- Row 3: Quantity / Find Total ----
        self.horizontalLayout_qty = QtWidgets.QHBoxLayout()
        self.horizontalLayout_qty.setObjectName("horizontalLayout_qty")

        self.label_qty = QtWidgets.QLabel(self.centralwidget)
        self.label_qty.setObjectName("label_qty")
        self.label_qty.setText("Quantity:")
        self.horizontalLayout_qty.addWidget(self.label_qty)

        self.lineEdit_qty = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_qty.setObjectName("lineEdit_qty")
        self.horizontalLayout_qty.addWidget(self.lineEdit_qty)

        self.btn_find_total = QtWidgets.QPushButton(self.centralwidget)
        self.btn_find_total.setObjectName("btn_find_total")
        self.btn_find_total.setText("Find Total")
        self.horizontalLayout_qty.addWidget(self.btn_find_total)

        self.verticalLayout_main.addLayout(self.horizontalLayout_qty)

        # ---- Row 4: Total display ----
        self.horizontalLayout_total = QtWidgets.QHBoxLayout()
        self.horizontalLayout_total.setObjectName("horizontalLayout_total")

        self.horizontalSpacer_total = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_total.addItem(self.horizontalSpacer_total)

        self.label_totalLabel = QtWidgets.QLabel(self.centralwidget)
        self.label_totalLabel.setObjectName("label_totalLabel")
        self.label_totalLabel.setText("Total:")
        self.horizontalLayout_total.addWidget(self.label_totalLabel)

        self.label_total = QtWidgets.QLabel(self.centralwidget)
        self.label_total.setObjectName("label_total")
        self.label_total.setStyleSheet("color: blue;")
        self.label_total.setText("Rs. 0")
        self.horizontalLayout_total.addWidget(self.label_total)

        self.verticalLayout_main.addLayout(self.horizontalLayout_total)

        MainWindow.setCentralWidget(self.centralwidget)

        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
